server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Logic agar Vue Router (jika dipakai nanti) tidak error 404 saat refresh
    location / {
        try_files $uri $uri/ /index.html;
    }
}